### PR TITLE
Solution to the prints of the trailing spaces and implementation of a Makefile

### PR DESCRIPTION
**Pull request by ignabelitzky**
This pull request addresses a few issues and improvements in the codebase:

**Trimming Trailing Spaces in Decrypted Message:**
I've modified the code to remove trailing spaces that appear when decrypting messages. This ensures that decrypted messages are displayed without any unintended whitespace.

**Adding Makefile for Improved Compilation:**
I've added a Makefile to streamline the compilation process. This makes it easier for developers to compile the project without needing to remember complex commands or configurations.

**Correcting Variable Types for Comparison:**
Several variables used in loops were updated to size_t to ensure correct comparison. This helps prevent potential issues related to variable overflow or incorrect comparisons.

**Adding .gitignore File:**
I've included a .gitignore file to specify which files and directories should be ignored by Git. This helps keep the repository clean by excluding unnecessary files and build artifacts.

Changes Made:

1. Removed trailing spaces in decrypted messages.
2. Added Makefile for easier compilation.
3. Updated variable types to size_t for correct comparisons.
4. Added .gitignore file.

Additional Notes:
Feel free to review the changes and provide any feedback or suggestions for improvement. Thanks for considering this pull request!

### CODE REVIEW

**Review by farukalpay — APPROVED** [review]
Thank you for your contribution. I have approved your pull request.

**Review by farukalpay — APPROVED** [review]
Thank you for your contribution. I have approved your pull request.

**Review by farukalpay — APPROVED** [review]
Thank you for your contribution. I have approved your pull request.

**Comment by ignabelitzky** [comment]
> Thank you for your contribution. I have approved your pull request.

Glad to hear that!!!

**Review by farukalpay — APPROVED** [review]

**Pull request merged**
